config/routes.rb
RailsParty::Application.routes.draw do
  resources :factories
  resources :widgets, :except => :new
  root :to => "factories#index"
  

end

app/models/factory.rb
class Factory < ActiveRecord::Base
  has_many :widgets
  
  validates :name, :location, :presence => true
  validates :name, :uniqueness => true
  validates :name, :length => {:maximum => 20}
end

# == Schema Information
#
# Table name: factories
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  location   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/models/widget.rb
class Widget < ActiveRecord::Base
  belongs_to :factory
  
  validates :name, :price, :description, :presence => true
  validates :price, :numericality => { :greater_than => 0.01 }
  validates :name, :uniqueness => true
end


# == Schema Information
#
# Table name: widgets
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  price       :decimal(, )
#  factory_id  :integer
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/factories_controller.rb
class FactoriesController < ApplicationController
  # GET /factories
  # GET /factories.xml
  def index
    @factories = Factory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @factories }
    end
  end

  # GET /factories/1
  # GET /factories/1.xml
  def show
    @factory = Factory.find(params[:id])
    @factory_widgets = Widget.find_all_by_factory_id(@factory[:id])
    @widget = Widget.new(:factory_id => @factory[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @factory }
    end
  end

  # GET /factories/new
  # GET /factories/new.xml
  def new
    @factory = Factory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @factory }
    end
  end
  
  # GET /factories/1/edit
  def edit
    @factory = Factory.find(params[:id])
  end

  # POST /factories
  # POST /factories.xml
  def create
    @factory = Factory.new(params[:factory])

    respond_to do |format|
      if @factory.save
        format.html { redirect_to(@factory, :notice => 'Factory was successfully created.') }
        format.xml  { render :xml => @factory, :status => :created, :location => @factory }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @factory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /factories/1
  # PUT /factories/1.xml
  def update
    @factory = Factory.find(params[:id])

    respond_to do |format|
      if @factory.update_attributes(params[:factory])
        format.html { redirect_to(@factory, :notice => 'Factory was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @factory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /factories/1
  # DELETE /factories/1.xml
  def destroy
    @factory = Factory.find(params[:id])
    @factory.destroy

    respond_to do |format|
      format.html { redirect_to(factories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  # GET /widgets
  # GET /widgets.xml
  def index
    @widgets = Widget.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @widgets }
    end
  end

  # GET /widgets/1
  # GET /widgets/1.xml
  def show
    @widget = Widget.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  # POST /widgets.xml
  def create
    @widget = Widget.new(params[:widget])
    
    if @widget.valid? and Factory.find_by_id(@widget[:factory_id])
      factory_valid = true
      @widget.save
    else
      factory_valid = false
      @widget.errors.add 'Factory ID', 'is not a existing valid Factory, asswipe'
    end

    respond_to do |format|
      if factory_valid
        format.html { redirect_to(@widget, :notice => 'Widget was successfully created.') }
        format.xml  { render :xml => @widget, :status => :created, :location => @widget }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @widget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.xml
  def update
    @widget = Widget.find(params[:id])

    respond_to do |format|
      if @widget.update_attributes(params[:widget])
        format.html { redirect_to(@widget, :notice => 'Widget was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @widget.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.xml
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to(widgets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/factories_helper.rb
module FactoriesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/factories/_form.html.erb
<%= form_for(@factory) do |f| %>
  <% if @factory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@factory.errors.count, "error") %> prohibited this factory from being saved:</h2>

      <ul>
      <% @factory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factories/edit.html.erb
<h1>Editing factory</h1>

<%= render 'form' %>

<%= link_to 'Show', @factory %> |
<%= link_to 'Back', factories_path %>

app/views/factories/index.html.erb
<h1>Listing factories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @factories.each do |factory| %>
  <tr>
    <td><%= factory.name %></td>
    <td><%= factory.location %></td>
    <td><%= link_to 'Show', factory %></td>
    <td><%= link_to 'Edit', edit_factory_path(factory) %></td>
    <td><%= link_to 'Destroy', factory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Factory', new_factory_path %>

app/views/factories/new.html.erb
<h1>New factory</h1>

<%= render 'form' %>

<%= link_to 'Back', factories_path %>

app/views/factories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @factory.name %>
</p>

<p>
  <b>Location:</b>
  <%= @factory.location %>
</p>

<p>
	<b>Widgets:</b>
	<ul>
	<% @factory_widgets.each do |widget| %>
		<li><%= link_to widget.name, widget %></li>
	<% end %>
	</ul>
<p>
	<%= render 'widgets/form' %>
</p>


<%= link_to 'Edit', edit_factory_path(@factory) %> |
<%= link_to 'Back', factories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsParty</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :factory_id %><br />
    <%= f.text_field :factory_id, :value => @widget[:factory_id] %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Price</th>
    <th>Description</th>
	<th>Factory ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @widgets.each do |widget| %>
  <tr>
    <td><%= widget.name %></td>
	<td><%= widget.price %></td>
    <td><%= widget.description %></td>
    <td><%= widget.factory_id %></td>
    <td><%= link_to 'Show', widget %></td>
    <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
    <td><%= link_to 'Destroy', widget, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @widget.name %>
</p>

<p>
  <b>Price:</b>
  <%= @widget.price %>
</p>

<p>
  <b>Description:</b>
  <%= @widget.description %>
</p>

<p>
  <b>Factory ID:</b>
  <%= @widget.factory_id %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>